### ISSUE TITLE
Citation required

### ISSUE THREAD

**Issue by jrosebr1** [gautamkumarjaiswal/Drowsiness-detection#1]
Hi @gautamkumarjaiswal -- Adrian Rosebrock here from PyImageSearch.com.

If noticed your [Medium article](https://medium.com/@gautamkumarjaiswal/development-of-real-time-drowsiness-detection-system-using-python-a87e3b2f58b6) as well as this GitHub repo.

I enjoyed your article; however, if you are going to use my near exact code you really need to cite the original article as well:

https://www.pyimagesearch.com/2017/05/08/drowsiness-detection-opencv/

You only cited the PyImageSearch blog versus my article tutorial which is very borderline plagiarism. 

Just wanted to open this issue and request that you update your repository and Medium article with the proper links.

**Comment by gautamkumarjaiswal** [comment]
Hi Adrain,
I modified citation and added link to your blog under reference section
(Medium and GitHub). Thanks for your suggestion.
